#[colors.primary]
#background = "#282A36"

general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 16
normal = { family = "Fira Code", style = "Medium" }

[window]
decorations = "Transparent"
opacity = 0.90
