#[colors.primary]
#background = "#282A36"

general.import = [
  #"~/.config/alacritty/catppuccin-mocha.toml"
]

[colors.primary]
background = "#1e1e2e"

[font]
size = 16
normal = { family = "Fira Code", style = "Medium" }

[window]
decorations = "Transparent"
opacity = 0.90
