#!/bin/zsh

# the BEST alias ever
alias please='echo "Of course, sir!\n" && sudo'

alias dot='cd $DOTFILES'
alias zmk='cd $HOME/Documents/zmk-config'
alias bat='batcat'

alias hconf='nvim $HOME/.config/hypr/hyprland.conf'
alias wconf='cd $HOME/.config/waybar'

# replace 'ls' with 'exa', if installed
unalias ls 2> /dev/null
ls() {
  if command -v eza &> /dev/null
  then
    eza -h --color=always --group-directories-first $@
  else
    command ls -h --color=auto --group-directories-first $@
  fi
}

unalias la 2> /dev/null
la() {
  if command -v eza &> /dev/null
  then
    eza -ah --color=auto --group-directories-first $@
  else
    command ls -ah --color=auto --group-directories-first $@
  fi
}

unalias ll 2> /dev/null
ll() {
  if command -v eza &> /dev/null
  then
    eza -alh --color=auto --group-directories-first $@
  else
    command ls -alh --color=auto --group-directories-first $@
  fi
}

alias tree='eza -T -I "__pycache__|.venv|venv|.git"'

#alias ls='ls -h --color=auto --group-directories-first'
#alias la='ls -ah --color=auto --group-directories-first'
#alias ll='ls -lah --color=auto --group-directories-first'

# basic navigation aliases
alias clr='clear'
alias cls='clear; ls'
alias uz='unzip'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias cp='cp -r' # copy directories recursively

#alias tree='tree -C -I "__pycache__|.venv|venv|.git"' # add colorization to tree

alias rnie="grep --exclude-dir={.venv,.git,__pycache__,node_modules} --binary-files=without-match -rniE"

# highlight grep match
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# mimic vim functions
alias :q='exit'

# Fix theme warning when opening appimage
# alias nim='GTK_THEME=Adwaita /usr/bin/nvim'

# editing and reliading
alias ze='nvim $ZDOTDIR/.zshrc'       # zshrc edit
alias zr='source $ZDOTDIR/.zshrc'     # zshrc reload
alias ae='nvim $DOTFILES/aliases'     # aliases edit
alias ar='source $DOTFILES/aliases'   # aliases reload
alias fe='nvim $DOTFILES/functions'   # functions edit
alias fr='source $DOTFILES/functions' # functions reload

alias history='nvim $ZDOTDIR/.zhistory'

# git aliases

alias gs='git status'
alias ga='git add -A'
alias gap='git add -p'
alias gm='git merge'
alias gl='git log --graph --oneline --branches -15'
alias glv='git log' # suposed to mean "git log verbose"
alias gc='git commit -v'
alias gb='git branch'
alias gck='git checkout'
alias gckb='git checkout -b'
alias gpl='git pull'
alias gf='git fetch'
alias gp='git push -u origin HEAD'
alias gr='git reset'
alias grh='git reset --hard'
alias grs='git reset --soft'
alias undocommit='git reset --soft HEAD~1'
alias gcl='git clean'
alias gcln='git clean -n'
alias gd='git diff'
alias gst='git stash'
alias gsl='git stash list'
alias gsa='git stash apply'
alias gsp='git stash push -m'
alias gpop='git stash pop'
alias gwl='git worktree list'
alias gwa='git worktree add'

# lazygit

alias lgit='lazygit'

# tmux

alias t='tmux'
alias ta='tmux attach-session -t'
alias tl='tmux list-sessions'
alias tkill='tmux kill-server'

# docker

alias dc="docker compose"
alias dcu="docker compose up -d"
alias dcub="docker compose up -d --build"
alias dcd="docker compose down"
alias dcl="docker compose -f docker-compose-local.yml"
alias dim="docker images"
alias dps='docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}\t"'
alias dpsa='docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}\t"'
alias dstopcontainers="docker ps | tail -n +2 | cut -d' ' -f1 | xargs docker stop"
alias drmcontainers="docker ps -a | tail -n +2 | cut -d' ' -f1 | xargs docker rm"
alias drmimages="docker images | tail -n +2 | command tr -s ' ' | cut -d' ' -f'3' | xargs docker rmi"

# python aliases

export DEFAULT_VENV_NAME='.venv'

alias p='python'
v() {
    if [[ -z $1 ]]; then
        VENV_NAME=$DEFAULT_VENV_NAME
    else
        VENV_NAME=$1
    fi
    python -m venv --system-site-packages $VENV_NAME
}
a() {
    if [[ -z $1 ]]; then
        VENV_NAME=$DEFAULT_VENV_NAME
    else
        VENV_NAME=$1
    fi
    source $VENV_NAME/bin/activate
}
alias d='deactivate'
alias r='pip install -r requirements.txt'
alias tr='pip install -r test_requirements.txt'
alias pp='python -m pytest -v'
alias var='v;a;r'
alias vart='var;tr'
alias pyt='poetry run pytest -W ignore'

alias al='alembic'
alias alr='alembic revision'
alias alra='al revision --autogenerate'
alias alu='POSTGRES_HOST=localhost alembic upgrade head'

# kubernetes
alias k="kubectl"
alias kns="kubectl ns"
alias kctx="kubectl ctx"
alias kg="kubectl get"
alias watch="watch "
alias kgp="kubectl get pods"
alias kdp="kubectl describe pod"
alias kgn="kubectl get nodes"
alias kdn="kubectl describe node"
alias kgs="kubectl get services"
alias kgsct="kubectl get secret"
alias kgds="kubectl get daemonset"
alias kgd="kubectl get deployment"
alias kgcm="kubectl get configmap"
alias kgsm="kubectl get servicemonitor"
alias kgpr="kubectl get prometheusrules"
alias kghpa="kubectl get HorizontalPodAutoscaler"
alias kgpa="kubectl get pod -A"
alias kge="kubectl get events"
alias kgpvc="kubectl get pvc"
alias kgpv="kubectl get pv"
alias kgsfs="kubectl get statefulset"
alias kd="kubectl describe"
alias kgl="kubectl logs -f"
alias kc="kubectl create -f"
alias pnr="kubectl get pod -A | grep -v Running"  # Usado para mostrar todos os pods com problemas.

# terraform

alias tf="terraform"

# nginx

alias nx="nginx"
