#!/usr/bin/bash

sudo apt install -y zsh curl make
git clone --recurse-submodules --depth 1 git@github.com:iagotito/dotfiles.git ~/.dotfiles
cd ~/.dotfiles
make fontsdownload
#make terminalsetup
make zshsetup
make zshdotfilessetup
