#wallpaper {
#    path = $HOME/.config/wallpapers/shaded.png
#}
#wallpaper {
#    path = $HOME/.config/wallpapers/car-with-full-moon-background.jpg
#}
#wallpaper {
#    path = $HOME/.config/wallpapers/landscape_pixel_art.jpg
#}
wallpaper {
    monitor =
    path = $HOME/.config/wallpapers/mountain.jpg
}
