#!/bin/bash

sudo apt install -y zsh curl make
if [[ ! -d ~/.dotfiles ]]; then
    git clone --recurse-submodules --depth 1 git@github.com:iagotito/dotfiles.git ~/.dotfiles
fi
cd ~/.dotfiles
make fontsdownload
make terminalsetup
make zshsetup
make zshdotfilessetup
