# prompt configuration

fpath=($DOTFILES/prompt $fpath)
autoload -Uz prompt_prettification_setup; prompt_prettification_setup

# zhistory

setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

# aliases

source $DOTFILES/aliases

# completion

#autoload -U compinit; compinit
#_comp_options+=(globdots)   # With hidden files
#source $ZDOTDIR/plugins/completion.zsh

